my_app/__init__.py
from flask import Flask
from my_app.fromulario.views import login

app = Flask(__name__)
app.register_blueprint(login)

my_app/fromulario/views.py
from flask import Blueprint, render_template, request

login = Blueprint('login', __name__)

@login.route('/')
def inicio():
    return render_template('login.html')

@login.route('/login',methods=['POST'])
def usuario():
    data = {
        #Datos de usuario
        'email' : request.form['email'],
        'pswr' : request.form["pswr"],
        #Prensentacion y datos
        'name' : request.form["name"],
        'apellidos' : request.form["apellidos"],
        'dni' : request.form["dni"],
        'presentacion' : request.form["presentacion"],
        #Formas de contacto
        'nmr' : request.form["nmr"],
        'cod_pos' : request.form["cod_pos"],
        'fb' : request.form["fb"],
        'ig' : request.form["ig"],
        'lkdn' : request.form["lkdn"],
        #Habilidades
        'skill1' : request.form["skill1"],
        'skill2' : request.form["skill2"],
        'skill3' : request.form["skill3"],
        'skill4' : request.form["skill4"],
        'skill5' : request.form["skill5"],
        #Experiencia laboral
        'work1' : request.form["work1"],
        'work2' : request.form["work2"],
        'work3' : request.form["work3"],
        #Experiencias laborales
        'workexp1_1' : request.form["workexp1_1"],
        'workexp1_2' : request.form["workexp1_2"],
        'workexp1_3' : request.form["workexp1_3"],
        'workexp2_1' : request.form["workexp2_1"],
        'workexp2_2' : request.form["workexp2_3"],
        'workexp3_1' : request.form["workexp3_1"],
        'workexp3_2' : request.form["workexp3_2"],
        'workexp3_3' : request.form["workexp3_3"],

        #Estudios 
        'sec' : request.form["sec"],
        'sup' : request.form["sup"],
        'mstr' : request.form["mstr"],
        'doc' : request.form["doc"],
        #Hobbies
        'hobbie1' : request.form["hobbie1"],
        'hobbie2' : request.form["hobbie2"],
        'hobbie3' : request.form["hobbie3"],
        'hobbie4' : request.form["hobbie4"]    
    }     
    
    return render_template('cv.html', data=data)

my_app/templates/cv.html
<!DOCTYPE html>
<HTML>
<head>
	<title> Curriculum</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
	<style>
      .row> div {
          padding: 20px;
          background-color: white;
          border: 2px solid black;
      }
    </style>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-4" align="left">
				<style>
					body {
        				background-color: #000000;
    				}
    				div {
        				
        				background-color: #700000;
    				}
    			</style>
				<center><img src="../static/static/imgs/foto.jpg" alt="Foto" style="width:250px"></<center>
				<hr/>
				<p>
					<h4> SOBRE MI </h4>
					<fieldset align="left">
						<p>
							{{data.presentacion}}
							<br>
						</p>
					</fieldset>
				</p>
				<p>
				<hr>
					<h4>CONTACTO</h4>
					<fieldset align="left">					
						<img src="https://assets.stickpng.com/images/5a4e2ef62da5ad73df7efe6e.png" alt="logo whatsapp" style="width:25px"> {{data.nmr}}
						<br>
						<br>
						<img src="https://www.pngmart.com/files/16/Black-Gmail-PNG-Photos.png" alt="logo mail" style="width:20px"> {{ data.email }}
						<br>
						<br>
						<img src="https://assets.stickpng.com/images/5ecec6ef73e4440004f09e75.png" alt="logo instagram" style="width:35px"> {{data.ig}}
						<br>
						<br>
						<img src="https://assets.stickpng.com/images/588891debc2fc2ef3a1860a2.png" alt="logo ubicacion" style="width:25px"> {{data.cod_pos}} 
						<br>
						<br>
						<img src="https://www.unipile.com/wp-content/uploads/2022/06/logo-facebook-noir.png" alt="logo facebook" style="width:25px" > {{data.fb}} 
						<br>
						<br>						
						<img src="https://icones.pro/wp-content/uploads/2021/03/icone-linkedin-ronde-noire.png" alt="logo linkedin" style="width:25px"> {{data.lkdn}} 
						<br>						
						
					</fieldset>
					<br>				
				</p>				
				<hr/>
				<p>				
					<h4>IDIOMAS</h4>
					<fieldset align="left">						
						        Español      <input type="checkbox" id="a" name="aa" value="a">
									<input type="checkbox" id="b" name="aa" value="b"> 
									<input type="checkbox" id="c" name="aa" value="c" checked >
									<input type="checkbox" id="d" name="aa" value="d" checked>
									<input type="checkbox" id="e" name="aa" value="e" checked>
									<input type="checkbox" id="f" name="aa" value="f" checked> 																		    
						<br>						
						        Inglés         <input type="checkbox" id="g" name="gg" value="g">
									<input type="checkbox" id="h" name="gg" value="h"> 
									<input type="checkbox" id="i" name="gg" value="i" >
									<input type="checkbox" id="j" name="gg" value="j">
									<input type="checkbox" id="k" name="gg" value="k">
									<input type="checkbox" id="l" name="gg" value="l" checked>
						<br>
						        Portugués  <input type="checkbox" id="m" name="mm" value="m">
								<input type="checkbox" id="n" name="mm" value="n"> 
								<input type="checkbox" id="o" name="mm" value="o" >
								<input type="checkbox" id="p" name="mm" value="p">
								<input type="checkbox" id="q" name="mm" value="q">
								<input type="checkbox" id="r" name="mm" value="r" checked>
					</fieldset>
					<br>
					<br><br>
					<h3>HOBBIES </h3>
					<br>
					<fieldset>
						<li>{{data.hobbie1}}</li>
						<li>{{data.hobbie2}}</li>
						<li>{{data.hobbie3}}</li>
						<li>{{data.hobbie4}}</li>
					</fieldset>			
				</p>		
			</div>
			<div class="col-8">
<br><br>
				<div class="col-12">					
					<h3><center><p style="color:white";> {{data.name}} {{data.apellidos}} </p></center></h3>
					<h4><center><p style="color:white";>Licenciado en Ciencia de la Computación</p></center></h4>
				</div>	
				<hr/>
				<h3><i>EXPERIENCIA LABORAL</i> </h3>
				<br>
				<b>{{work1}} </b>
				<fieldset>
					<li>{{data.workexp1_1}}</li>
					<li>{{data.workexp1_2}}</li>
					<li>{{data.workexp1_3}}</li>
					
				</fieldset>
				<br><br>
				<b>{{data.work2}} </b>
				<fieldset>
					<li>{{data.workexp2_1}}</li>
					<li>{{data.workexp2_2}}</li>
					<li>{{data.workexp2_3}}</li>
				</fieldset>
				<br><br>
				<b>{{data.work3}} </b>
				<fieldset>
					<li>{{data.workexp3_1}}</li>
					<li>{{data.workexp3_2}}</li>
					<li>{{data.workexp3_3}}</li>
				</fieldset>
				<br><br>
				<h3><i>FORMACIÓN</i> </h3>
				<br>
				<p>
					<fieldset>
						-->{{data.sec}} 
						<br><br>
						-->{{data.sup}} 
						<br><br>
						-->{{data.mstr}} 
						<br><br>
						-->{{data.doc}} 
					</fieldset>
				</p>
				
				<hr/>
				<h3><i>COMPETENCIAS </i> </h3>
				<br>
				<fieldset>
					<li>{{data.skill1}}</li>
					<li>{{data.skill2}}</li>
					<li>{{data.skill3}}</li>
					<li>{{data.skill4}}</li>
					<li>{{data.skill5}}</li>
				</fieldset>
				</div>	
		</div>
	</div>
</HTML>	
						

my_app/templates/login.html
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="../static/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="../static/static/css/estilos.css">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../static/static/js/main.js"></script>
    
</head>

<body>
    <main>
        <div class="contenedor__todo">
            <div class="contenedor__login-register">
                <form action="{{ url_for('login.usuario') }}" method="post">
                    <div class="wrap">
                        <ul class="tabs">
                            <li><a href="#tab1"><span class="tab-text">Usuario</span></a></li>
                            <li><a href="#tab2"><span class="tab-text">Datos personales</span></a></li>
                            <li><a href="#tab3"><span class="tab-text">Habilidades</span></a></li>
                            <li><a href="#tab4"><span class="tab-text">Experiencia laboral</span></a></li>
                            <li><a href="#tab5"><span class="tab-text">Estudios</span></a></li>
                            <li><a href="#tab6"><span class="tab-text">Hobbies</span></a></li>
                            <li><a href="#tab7"><span class="tab-text">Contacto</span></a></li>
        
                        </ul>
        
                        <div class="secciones">
                            <article id="tab1">
                                <h1>Usuario:</h1>
                                <br>
                                <input type="text" id="email" name="email" placeholder="E-mail" required class="validate">
                                <br>
                                <input type="password" id="pswr" name="pswr" placeholder="Contraseña" required class="validate">
                                <br>
                            </article>
                            <article id="tab2">
                                <h1>Datos personales</h1>
                                <br>
                                <input type="text" id="name" name="name" placeholder="Nombre" required class="validate">
                                <br>
                                <input type="text" id="apellidos" name="apellidos" placeholder="Apellidos" required
                                    class="validate">
                                <br>
                                <input type="text" id="dni" name="dni" placeholder="Dni" required class="validate">
                                <br>
                                <input type="text" id="presentacion" name="presentacion" placeholder="Presentate" required
                                    class="validate">
                                <br>
                            </article>
                            <article id="tab3">
                                <h1>Habilidades:</h1>
                                <input type="text" id="skill1" name="skill1" placeholder="Ingresa tu habiilidad 1" required
                                    class="validate">
                                <br>
                                <input type="text" id="skill2" name="skill2" placeholder="Ingresa tu habiilidad 2" required
                                    class="validate">
                                <br>
                                <input type="text" id="skill3" name="skill3" placeholder="Ingresa tu habiilidad 3" required
                                    class="validate">
                                <br>
                                <input type="text" id="skill4" name="skill4" placeholder="Ingresa tu habiilidad 4" required
                                    class="validate">
                                <br>
                                <input type="text" id="skill5" name="skill5" placeholder="Ingresa tu habiilidad 5" required
                                    class="validate">
                                <br>
        
                            </article>
                            <article id="tab4">
                                <h3>Experiencia laboral 1:</h3>
                                <input type="text" id="work1" name="work1" placeholder="Puesto de trabajo" required
                                    class="validate">
                                <br>
                                <h4>Tres labores que cumplia en ese puesto:</h4>
                                <input type="text" id="workexp1_1" name="workexp1_1" placeholder="Labor 1" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp1_2" name="workexp1_2" placeholder="Labor 2" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp1_3" name="workexp1_3" placeholder="Labor 3" required
                                    class="validate">
                                <br>
                                <br>
                                <h3>Experiencia laboral 2:</h3>
                                <input type="text" id="work2" name="work2" placeholder="Puesto de trabajo" required
                                    class="validate">
                                <br>
                                <h4>Tres labores que cumplia en ese puesto:</h4>
                                <input type="text" id="workexp2_1" name="workexp2_1" placeholder="Labor 1" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp2_2" name="workexp2_2" placeholder="Labor 2" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp2_3" name="workexp2_3" placeholder="Labor 3" required
                                    class="validate">
                                <br>
                                <br>
                                <h3>Experiencia laboral 3:</h3>
                                <input type="text" id="work3" name="work3" placeholder="Puesto de trabajo" required
                                    class="validate">
                                <br>
                                <h4>Tres labores que cumplia en ese puesto:</h4>
                                <input type="text" id="workexp3_1" name="workexp3_1" placeholder="Labor 1" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp3_2" name="workexp3_2" placeholder="Labor 2" required
                                    class="validate">
                                <br>
                                <input type="text" id="workexp3_3" name="workexp3_3" placeholder="Labor 3" required
                                    class="validate">
                                <br>
        
        
                            </article>
                            <article id="tab5">
                                <h1>Estudios:</h1>
                                <br>
                                <input type="text" id="sec" name="sec" placeholder="Donde hizo su Educacion secundaria" required
                                    class="validate">
                                <br>
                                <input type="text" id="sup" name="sup" placeholder="Donde hizo su Educacion superior" required
                                    class="validate">
                                <br>
                                <input type="text" id="mstr" name="mstr" placeholder="Donde hizo su Maetria" required
                                    class="validate">
                                <br>
                                <input type="text" id="doc" name="doc" placeholder="Donde hizo su Doctorado" required
                                    class="validate">
                                <br>
                            </article>
                            <article id="tab6">
                                <h1>Hobbies:</h1>
                                <br>
                                <input type="text" id="hobbie1" name="hobbie1" placeholder="Hobbie" required class="validate">
                                <br>
                                <input type="text" id="hobbie2" name="hobbie2" placeholder="Hobbie" required class="validate">
                                <br>
                                <input type="text" id="hobbie3" name="hobbie3" placeholder="Hobbie" required class="validate">
                                <br>
                                <input type="text" id="hobbie4" name="hobbie4" placeholder="Hobbie" required class="validate">
                                <br>
                            </article>
                            <article id="tab7">
                                <h1>Contacto</h1>
                                <p>En caso no tengas alguna coloca "-"</p>
                                <br>
                                <input type="text" id="nmr" name="nmr" placeholder="Numero de telefono" required
                                    class="validate">
                                <br>
                                <input type="text" id="cod_pos" name="cod_pos" placeholder="Codigo postal" required
                                    class="validate">
                                <br>
                                <input type="text" id="fb" name="fb" placeholder="Facebook" required class="validate">
                                <br>
                                <input type="text" id="ig" name="ig" placeholder="Instagram" required class="validate">
                                <br>
                                <input type="text" id="lkdn" name="lkdn" placeholder="Linkedin" required class="validate">
                                <br>
                            </article>
                            <br>
                            <input type="submit" id="send-register" name="signup" value="Registrar" />
        
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    
    <script type="text/javascript" src="../static/static/js/localstorage.js"></script>
    <script type="text/javascript" src="../static/static/js/script.js"></script>

</body>

</html>